apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: peatch
  name: peatch
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      service: peatch
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        service: peatch
    spec:
      containers:
        - image: maksim1111/peatch:latest
          name: peatch
          imagePullPolicy: IfNotPresent
          command: [ "/app/api" ]
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "512Mi"
          volumeMounts:
            - mountPath: /app/config.yml
              name: peatch-config
              subPath: config.yml
      volumes:
        - name: peatch-config
          secret:
            secretName: peatch-secrets
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: peatch
  name: peatch
  namespace: default
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    service: peatch
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: peatch
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
spec:
  ingressClassName: nginx
  rules:
    - host: api.peatch.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: peatch
                port:
                  number: 8080