apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    service: peatch
  name: peatch
  namespace: default
spec:
  serviceName: "peatch"
  replicas: 1
  selector:
    matchLabels:
      service: peatch
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 0
  template:
    metadata:
      labels:
        service: peatch
    spec:
      containers:
        - image: maksim1111/peatch:latest
          name: peatch
          imagePullPolicy: IfNotPresent
          command: [ "/app/main" ]
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "512Mi"
          volumeMounts:
            - mountPath: /app/storage
              subPath: storage
              name: peatch-data
            - mountPath: /app/config.yml
              name: peatch-config
              subPath: config.yml
          env:
            - name: CONFIG_FILE_PATH
              value: /app/config.yml
          readinessProbe:
            exec:
              command: [ "sqlite3", "/app/storage/db.sqlite", ".tables" ]
            initialDelaySeconds: 0
            periodSeconds: 5
            timeoutSeconds: 2
      volumes:
        - name: peatch-config
          secret:
            secretName: peatch-secrets
  volumeClaimTemplates:
    - metadata:
        name: peatch-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
        storageClassName: "do-block-storage"

---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: peatch
  name: peatch
  namespace: default
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    service: peatch
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: peatch
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
spec:
  ingressClassName: nginx
  rules:
    - host: api.peatch.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: peatch
                port:
                  number: 8080