---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-secrets
  namespace: default
spec:
  encryptedData:
    POSTGRES_DB: AgBStab6Iiqf4MI3STqDlTBpwtW2M2m6xv40FbOOHQFgTCjwpOX/Xk9JB+yY2XR2oDPUXzOuaQkuXFPihlBrRA0HogZsetSrF786s1YIaOhVWCvmWs9FFQXhSnSs18dgiHEHcMPfWmtLT0Euz5uJQgwE3nhRoqHMIUbAtsakXS5dMmn4pOecfNzIhxLxusdGB3/F99GOG/eP2kBWd4Gf6r1RqL0QCEj7PRuHCKL0NrZ9CdVuPcf8rxOb+i+pqu0Fe/tT0xIBnQuurRIJuUdKkfzXjFOlrGZtcsC2IG08Ui+G35axm5PJewnVoUjcfW5FtpNXEwAPDChjHURzPZoDNYyFJU/tr5qCNRceCNPC/tn3/irXt+3IpaonsnseQ3A9tfKNxFRQteEpsgmnWwZur2MOiyHvi/8NeCFmYCbdk6xXlVjx65JDnXe38tfOUtiMKFB3ryXJikHYlS3F7uaYEdNvYqyGEikAy1FHmS48CsLR8N5V7OGF9zskiYwdevcoD29Chpz4UIdTeKIBMRv4Lh1wNgmOwoZ5glQGHIUjfXwgC0373BrwpxWTO6W2AOc0erGLR0Z4PorMP5jl+yseco6PQ3kt3MLepZEaEmvGlzk+5NPQpQGIclPeyFZRI+AneCVl1mDlOZGOEpMpbQGSJu2yjjGRBgl1k1nKamCQgQBWv9Lc5j5F2Hnj+yhFmm0OUHsMF8oz4Vo=
    POSTGRES_PASSWORD: AgCXoG7GTTtCydnukkwR2LMdVuwrrdVENChh1Vx0dX0Ug0JncdHhzIKv+4ZeyQs2aD+TF2z7FNErIdnY3MvuItqVB0MVK/sR3meZPMKWSSioOVPHd9Tp5gOH8aN0Y621Aoki9szfOCvo+D3HzdK5t/kdQfL/SWx4qHuw2VYlnhCMaIZzHeaQXqYM+0a3Uxp4tZbQaQkJMH0d7u1Jw4s73RVRphxV9eF0JffL2xfP6Nv3TtFDomQZjzJmpWzZipfIN7eCuJf3p5HZI2WE3OQh5DeM6I9K9a1bpetJiZxq1WxOAbVY9F3eNomhpanIFqm9ZpBA3fFCENpWII/ThqBOdld7uIIf8HXtFbPQixJ/d9gB7EyrSMGZyU95BIsI2quP5XQmp9Q7Ej41fdBEC9DWqb6foAz1mIUBJwtrgu7fCoSoudebNe+V7ckDXVeQMLkZ1iGVmciK1G+LGkPF8wVNikUskMR7YpeGK99LFctu3wP6sMAmbKzlWO6b1Kb35dnFvpNeQHHNz3HwdM9xO0evgCNxzI9471XL70mpia1F8ubgFkTcddMvWRXs6Bu485yrIF/Dhrj2D4BxypWT/HoSi63He85xBMpKYAlqjyvU3Zm0cN06aGr/4dpnWwjCRShEa713TPBig8znk00oySsK63pmZ5/OjxtADuvOTcJNfvPsDkmVZbtKSHzYk3mh2VxF0z2ZLMfrU3ztWAWd2nj4XkVI
  template:
    metadata:
      creationTimestamp: null
      name: postgres-secrets
      namespace: default
