---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-secrets
  namespace: default
spec:
  encryptedData:
    POSTGRES_DB: AgCwFUduM1vYfat+gLJCucTB+gl+OQX7TPUalmIc+rz2YGFjmqVN4X39UDA6sGdCMjmFBPKiwz+e/HyryReDLR+XdP2nskPdpPkYJAEsCEFCNAy2ACZ/gBCq6e5yRNHFIKwhjPLCBXJrLTmZ6U/U0zutEgMT2DcvKNFPOz4UXVQ441OwS9M5eVnTMPGJm6V11BkC2s6hX4f3vkmgsAfe5FubjrXOjtyH7XuZht4A9b0DawCkBx5/pUdO1rIUBABoHvEVZEOy40nm2fc1LPf22Hu44dUMKcV4G+zDZA00dAMqRq+HlgKcX32W2gqJ7IpnTciyO3TAroLyX6ISmVLw+cFmjtnBq5dPIKTHxBRFdjeRTchhbALG3co0Dt90p185aFHtphJeY9v2ivwMz4EyzmAVr5/DCzSTvP4fD5WGaXGoSGyYklwxB7+ezT1CNE/8GnZAQ8J53AqXzUJXuTyU1J2ZcidDNEgiLgS1Tde7qv6m+Kna90NksEYNIsZpMvyoAe0ZLiXXcMsO04SgG/e5oPsjEjtXQvtzyc314b3/SGliopHrxDqe/VRvp+fbonlUnJvbdAdCxoK0kBPi1tU0ETeIxxEcgR/nrgdAEt9qSgF6m3OYHaL+3znd9qAPAvhGzM4gOxDwIUliRsNBvXS/f4u+pp4npyQG5W0JvHYoC62m3ihnPwd7oS8RZRyO5XDIFIoah7zEl+IIKA==
    POSTGRES_PASSWORD: AgBrrHYgX/W2dcxcPf7jSwuFnWbxu/y2S8sflf/SXZj48mOnqUyhoQy24vzzWBnyFRRCbfdP2pWQML0BcQwLrPQNerhfm+c9KXIJg23eNv6NV3aWWYpoz3SfhpblFnegYV2F1UlqMhgiMax6+mrO7zsW+A8+QjApbZkTD1Yhl6JNbH3D7YOjkfLLu9ehcGKlG0iziWFa010xGzDtCVs/LzhjP9DwKygr2bsE3tA4uwZpvbCT47BSn1g3nNGwHwyTXh6qThpn0LGqbsrH2xpNgbkPIGVByXREdZTCN5XZqlQx8LKxsvqxYdLj0dsSgrF9ByXtmqQdQtm4R2EBhddBJlYrPHMV25SvyifKrKLgMyn6OsUkNPH79tuPQFNq8FUMaMgoJkB+NgkAWc8hJQ+9eOeccXgCiXfWnofOfvZPHd+2R0IHDKTYcx2jZrMqjGIHek0A3su7dbwE/HNwTIDWehHfgrBoVfYzgrdoaNvUgJBaGpv8KUYMVccsYOTQBualdpjII9IU1HHcxNAThgHCzgwYbQqk3hn30fahpsX7B2wwPQmje6Wmfsijoc/zpBseRVoUIEZJ/gMvr6PZzXumOIuSK4X98EyNuiAraNt149qScbqJJvQoeNYUWTkULMaV2LPGUQvbeF10N9fADX8wKtq7nBVMk1vUrEb9s8+vpeBQmJ6iHVgaiuzSU93EDl5HUSWnHp0kJozlxg==
  template:
    metadata:
      creationTimestamp: null
      name: postgres-secrets
      namespace: default
